name: Build and Deploy
on:
  push:
    branches: main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup ENV
        run: |
          sudo echo "${{ secrets.ENV }}" > .env
      - name: Maven Build
        run: |
          mvn clean package
      # ---------- HOST ----------
      - name: Checkout (host)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo rm -rf lpi-source
            git clone ${{ github.server_url }}/${{ github.repository }} lpi-source
      - name: Setup ENV (host)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo echo "${{ secrets.ENV }}" > lpi-source/.env
      - name: Copy Artifact (host)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "target/lpi.jar"
          target: lpi-source
      - name: Deploy (host)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd lpi-source
            sudo docker-compose up -d --no-recreate maria_db
            sudo docker-compose up -d --no-deps --build api_service
