name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install Maven
        run: sudo apt-get install -y maven
      - name: Build with Maven
        run: mvn package
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            mkdir -p /opt/lpi
            cd /opt/lpi
            scp -r ${{ github.workspace }}/target/lpi.jar ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/opt/lpi/
            ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "java -jar /opt/lpi/lpi.jar"
